import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { NumberButton } from "../components/NumberButton";
import { MainBoard } from "../components/MainBoard";
import { CalculateDisplay } from "../components/CalculateDisplay";
import { OperationBoard } from "../components/OperationButton";
import { KeyboardNumber } from "../components/KeyboardNumber";
import { KeyboardOperations } from "../components/KeyboardOperations";
import { ButtonBackspace } from "../components/buttonBackSpace";
import { KeyboardDisplay } from "../components/Keyboard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Desafio Calculadora OrangeTech | DIO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainBoard>
        <CalculateDisplay>0254021</CalculateDisplay>

        <KeyboardDisplay>
          <KeyboardNumber>
            <OperationBoard>AC</OperationBoard>
            <OperationBoard>%</OperationBoard>
            <OperationBoard>{ButtonBackspace}</OperationBoard>
            <NumberButton>1</NumberButton>
            <NumberButton>2</NumberButton>
            <NumberButton>3</NumberButton>
            <NumberButton>4</NumberButton>
            <NumberButton>5</NumberButton>
            <NumberButton>6</NumberButton>
            <NumberButton>7</NumberButton>
            <NumberButton>8</NumberButton>
            <NumberButton>9</NumberButton>
            <NumberButton>0</NumberButton>
            <NumberButton>.</NumberButton>
          </KeyboardNumber>
          <KeyboardOperations>
            <OperationBoard>+</OperationBoard>
            <OperationBoard>-</OperationBoard>
            <OperationBoard>x</OperationBoard>
            <OperationBoard>/</OperationBoard>
            <OperationBoard>=</OperationBoard>
          </KeyboardOperations>
        </KeyboardDisplay>
      </MainBoard>
    </>
  );
}
